name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature relate to?
      options:
        - Notion Integration
        - Agent System (Dialectics)
        - API Endpoints
        - Diff Logger / Training Data
        - Poller System
        - Configuration
        - Documentation
        - Testing
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Would greatly improve workflow)
        - Medium (Would be nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        As a [type of user]
        I want to [do something]
        So that [I can achieve some goal]
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If you have ideas about implementation, share them here
      placeholder: Technical details, API changes, architecture considerations, etc.

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples or mockups if applicable
      placeholder: |
        Code examples, API request/response examples, UI mockups, etc.

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature would introduce breaking changes
        - label: This feature would require database migrations
        - label: This feature would require configuration changes

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute?
      options:
        - label: I am willing to submit a PR to implement this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: Links to similar features in other projects, research papers, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have checked the documentation to ensure this feature doesn't already exist
          required: true
        - label: I have provided a clear description of the feature and its use case
          required: true
