"""
Executive Command Center Integration Module

Automatically updates the Executive Command Center page with:
- Real-time insights and metrics
- Cross-linking between databases
- Executive summaries
- Visual enhancements with emojis and formatting
"""

import asyncio
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional
from loguru import logger
from notion_client import AsyncClient

from config.settings import settings


class CommandCenterSync:
    """Manages Executive Command Center updates and insights"""

    def __init__(self, notion_client: AsyncClient):
        self.client = notion_client
        self.command_center_id = "2eac8854-2aed-80cd-8f2a-e96b2e5d52c8"

    async def generate_executive_summary(self, intent_id: str, classification: Dict[str, Any]) -> str:
        """Generate rich executive summary with emojis and structure"""

        risk_emoji = {
            "Low": "🟢",
            "Medium": "🟡",
            "High": "🔴"
        }

        agent_emoji = {
            "The Entrepreneur": "🚀",
            "The Quant": "📊",
            "The Auditor": "🔍"
        }

        risk = classification.get("risk", "Medium")
        agent = classification.get("agent", "The Entrepreneur")
        impact = classification.get("impact", 5)
        rationale = classification.get("rationale", "")

        summary = f"""
{risk_emoji.get(risk, "⚪")} **Risk Level**: {risk}
{agent_emoji.get(agent, "🤖")} **Assigned Agent**: {agent}
⚡ **Impact Score**: {impact}/10

**AI Analysis**:
{rationale}

---
*Generated by Executive Mind Matrix*
"""
        return summary.strip()

    async def add_dialectic_summary(self, intent_id: str, dialectic_result: Dict[str, Any]) -> None:
        """Add dialectic analysis summary to Executive Intent page"""

        try:
            synthesis = dialectic_result.get("synthesis", "")
            recommended_path = dialectic_result.get("recommended_path", "")
            conflicts = dialectic_result.get("conflict_points", [])
            growth_rec = dialectic_result.get("growth_recommendation", "")
            risk_rec = dialectic_result.get("risk_recommendation", "")

            # Create rich formatted summary
            summary_blocks = [
                {
                    "object": "block",
                    "type": "heading_2",
                    "heading_2": {
                        "rich_text": [{"text": {"content": "🤝 Dialectic Analysis Results"}}]
                    }
                },
                {
                    "object": "block",
                    "type": "callout",
                    "callout": {
                        "icon": {"emoji": "🚀"},
                        "color": "green_background",
                        "rich_text": [{"text": {"content": f"Growth Perspective: Recommends Option {growth_rec}"}}]
                    }
                },
                {
                    "object": "block",
                    "type": "callout",
                    "callout": {
                        "icon": {"emoji": "🔍"},
                        "color": "red_background",
                        "rich_text": [{"text": {"content": f"Risk Perspective: Recommends Option {risk_rec}"}}]
                    }
                },
                {
                    "object": "block",
                    "type": "heading_3",
                    "heading_3": {
                        "rich_text": [{"text": {"content": "💡 Synthesis"}}]
                    }
                },
                {
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [{"text": {"content": synthesis}}]
                    }
                },
                {
                    "object": "block",
                    "type": "heading_3",
                    "heading_3": {
                        "rich_text": [{"text": {"content": "🎯 Recommended Path"}}]
                    }
                },
                {
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [{"text": {"content": recommended_path}}]
                    }
                }
            ]

            # Add conflict points if any
            if conflicts:
                summary_blocks.append({
                    "object": "block",
                    "type": "heading_3",
                    "heading_3": {
                        "rich_text": [{"text": {"content": "⚔️ Key Conflicts"}}]
                    }
                })

                for conflict in conflicts:
                    summary_blocks.append({
                        "object": "block",
                        "type": "bulleted_list_item",
                        "bulleted_list_item": {
                            "rich_text": [{"text": {"content": conflict}}]
                        }
                    })

            # Append blocks to the intent page
            await self.client.blocks.children.append(
                block_id=intent_id,
                children=summary_blocks
            )

            logger.info(f"Added dialectic summary to intent {intent_id[:8]}")

        except Exception as e:
            logger.error(f"Error adding dialectic summary: {e}")

    async def create_action_pipe_with_context(
        self,
        title: str,
        description: str,
        source_intent_id: str,
        priority: str = "Medium"
    ) -> str:
        """Create Action Pipe with rich formatting and cross-links"""

        try:
            # Add emoji based on priority
            priority_emoji = {
                "High": "🔥",
                "Medium": "⚡",
                "Low": "📝"
            }

            enhanced_title = f"{priority_emoji.get(priority, '📝')} {title}"

            # Create action pipe entry
            response = await self.client.pages.create(
                parent={"database_id": settings.notion_db_action_pipes},
                properties={
                    "Action_Title": {
                        "title": [{"text": {"content": enhanced_title}}]
                    },
                    "Scenario_Options": {
                        "rich_text": [{"text": {"content": description}}]
                    },
                    "Approval_Status": {
                        "select": {"name": "Pending"}
                    },
                    "Intent": {
                        "relation": [{"id": source_intent_id}]
                    }
                }
            )

            action_id = response["id"]
            logger.info(f"Created Action Pipe with enhanced formatting: {action_id[:8]}")

            return action_id

        except Exception as e:
            logger.error(f"Error creating action pipe: {e}")
            raise

    async def get_system_metrics(self) -> Dict[str, Any]:
        """Calculate system-wide metrics for Command Center"""

        try:
            now = datetime.now()

            # Get counts from each database
            inbox_response = await self.client.databases.query(
                database_id=settings.notion_db_system_inbox,
                filter={"property": "Status", "select": {"equals": "Unprocessed"}}
            )

            intents_response = await self.client.databases.query(
                database_id=settings.notion_db_executive_intents,
                filter={"property": "Status", "select": {"equals": "Ready"}}
            )

            # Action Pipes uses "Approval_Status" not "Status"
            actions_response = await self.client.databases.query(
                database_id=settings.notion_db_action_pipes,
                filter={"property": "Approval_Status", "select": {"equals": "Pending"}}
            )

            # Also get total counts
            all_intents = await self.client.databases.query(
                database_id=settings.notion_db_executive_intents
            )

            all_actions = await self.client.databases.query(
                database_id=settings.notion_db_action_pipes
            )

            metrics = {
                "pending_inbox": len(inbox_response.get("results", [])),
                "ready_intents": len(intents_response.get("results", [])),
                "pending_actions": len(actions_response.get("results", [])),
                "total_intents": len(all_intents.get("results", [])),
                "total_actions": len(all_actions.get("results", [])),
                "last_updated": now.isoformat()
            }

            return metrics

        except Exception as e:
            logger.error(f"Error calculating metrics: {e}")
            return {}

    async def update_command_center_metrics(self) -> None:
        """Update the Metrics & Insights section of Command Center"""

        try:
            metrics = await self.get_system_metrics()

            # Find the System Status block
            blocks = await self.client.blocks.children.list(
                block_id=self.command_center_id
            )

            # Create metrics callout
            metrics_text = f"""
📊 **System Overview** (Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')})

📥 Pending Inbox Items: {metrics.get('pending_inbox', 0)}
🎯 Ready Intents: {metrics.get('ready_intents', 0)} (Total: {metrics.get('total_intents', 0)})
⚡ Pending Actions: {metrics.get('pending_actions', 0)} (Total: {metrics.get('total_actions', 0)})

Status: 🟢 All systems operational
"""

            # Append metrics block
            await self.client.blocks.children.append(
                block_id=self.command_center_id,
                children=[
                    {
                        "object": "block",
                        "type": "callout",
                        "callout": {
                            "icon": {"emoji": "📊"},
                            "color": "blue_background",
                            "rich_text": [{"text": {"content": metrics_text.strip()}}]
                        }
                    }
                ]
            )

            logger.info("Updated Command Center metrics")

        except Exception as e:
            logger.error(f"Error updating Command Center metrics: {e}")

    async def enhance_intent_formatting(self, intent_id: str, classification: Dict[str, Any]) -> None:
        """Add rich formatting and insights to an Executive Intent"""

        try:
            summary = await self.generate_executive_summary(intent_id, classification)

            # Add summary block to intent page
            await self.client.blocks.children.append(
                block_id=intent_id,
                children=[
                    {
                        "object": "block",
                        "type": "callout",
                        "callout": {
                            "icon": {"emoji": "🧠"},
                            "color": "blue_background",
                            "rich_text": [{"text": {"content": summary}}]
                        }
                    }
                ]
            )

            logger.info(f"Enhanced formatting for intent {intent_id[:8]}")

        except Exception as e:
            logger.error(f"Error enhancing intent formatting: {e}")
